### ISSUE TITLE
support for exec

### ISSUE THREAD

**Issue by Tim-Erwin** [d11wtq/dockerpty#30]
This library works great for start(). Could we get support for dockerclient.execute()?

**Comment by d11wtq** [comment]
:+1:

**Comment by Tim-Erwin** [comment]
Great :)

**Comment by j-bennet** [comment]
Yes please! Any word on this, @d11wtq ?

**Comment by d11wtq** [comment]
Maybe somebody could send a PR for it? :) It certainly appears that it would be possible to do based on this https://github.com/docker/docker-py/pull/363/files#diff-5262437d121a30fc85a81c4b1da57e4bR545 which provides the needed streams, plugged in by doing something along the lines of the start method https://github.com/d11wtq/dockerpty/blob/master/dockerpty/pty.py#L126 (however some things will need renaming/moving around to account for the two approaches).

**Comment by allonhadaya** [comment]
This would be great :+1:

**Comment by TomasTomecek** [comment]
I am planning to work on this soon. I've already did some brief analysis and realised that method [`sockets()`](https://github.com/d11wtq/dockerpty/blob/master/dockerpty/pty.py#L174) will probably require rewrite since it's tied to containers and `attach_socket` now.
