### ISSUE TITLE
Streams closing due to recoverable errors when reading

### ISSUE THREAD

**Issue by bschmeck** [d11wtq/dockerpty#32]
I've observed my streams closing due to recoverable errors (generally EWOULDBLOCK) when reading.

`Stream.write` sits in a while loop to retry after recoverable errors, is there a reason `Stream.read` doesn't?  I've had success modifying `Stream.read` to sit in a while loop, but am worried that I'm missing a corner case.

**Comment by aanand** [comment]
No, this sounds like a reasonable change. Could you submit a PR?

If there are corner cases, manual testing in a bunch of scenarios should hopefully ferret them out (opening up vim in a container is usually a good one).
