### ISSUE TITLE
Is dockerpty ready for a 0.3.3 release?

### ISSUE THREAD

**Issue by rmohr** [d11wtq/dockerpty#37]
@d11wtq, @aanand  do you think that dockerpty is ready for a 0.3.3 release? I'd love to bring the newest changes into the fedora repos. I have [this bugzilla report](https://bugzilla.redhat.com/show_bug.cgi?id=1172357) already way too long open ;)

**Comment by aanand** [comment]
I want to get #36 merged first, but after that, yep - definitely release time.

**Comment by d11wtq** [comment]
I think this one is done :)
