### ISSUE TITLE
dockerpty causing docker-compose run to exit with return code 1?

### ISSUE THREAD

**Issue by heidarxvpn** [d11wtq/dockerpty#41]
Hi,

I have this issue open on docker/compose and I think it might possibly belong here. I've tried looking around but I can pinpoint the problem. Can anyone help?

https://github.com/docker/compose/issues/1424

Thanks!

**Comment by josephpage** [comment]
Also probably related to docker/compose#1483 and docker/compose#1429

**Comment by aanand** [comment]
Thanks for reporting - this was already known but we hadn't gotten round to fixing it and I didn't realise it had broken Compose. Fixed in https://github.com/d11wtq/dockerpty/pull/44.
