### ISSUE TITLE
Attaching to docker containers fails when specifying a log driver

### ISSUE THREAD

**Issue by alf** [d11wtq/dockerpty#51]
I came here from https://github.com/docker/compose/issues/2448 since I'm bitten by the same issue. @glenbot [pointed out](https://github.com/docker/compose/issues/2448#issuecomment-161722916) that the problem is caused by [pty.py:188](https://github.com/d11wtq/dockerpty/blob/master/dockerpty/pty.py#L188) where the docker client is used to attach to the socket. Here dockerpty specifies `'logs': 1 ` which breaks when the container is running with a log driver.

Here's an example program that exercises the issue:

```python
import dockerpty
import docker
from docker.utils import kwargs_from_env

client = docker.Client(**kwargs_from_env())
container = client.create_container(
    image='busybox:latest',
    stdin_open=True,
    tty=True,
    command='/bin/sh',
    host_config={"LogConfig": {
        "Type": "none"
    }}
)

dockerpty.start(client, container['Id'], interactive=True)
```

I've verified that changing the value of logs to 0 makes the test program work as expected.

**Comment by alf** [comment]
According to the [documentation](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.17/#attach-to-a-container) of the docker remote API:

```logs – 1/True/true or 0/False/false, return logs. Default false```

I understand this to mean that by setting `logs` to `True` we're asking the docker daemon to send us the logged output of the container so far. Looking at [attach_socket](https://github.com/docker/docker-py/blob/master/docker/api/container.py#L25) in `docker-py` we see that the default is for `logs` is `False`.

To be able to fix this issue in docker-compose we need some way to make dockerpty use `'logs': 0`. This should ideally be an option to dockerpty.start. 

In addition someone who knows the history of the current default might want to look into whether it is worth changing it to match the defaults in the Docker API and in docker-py. I suspect the answer is no. :)

**Comment by aanand** [comment]
Yeah, ideally the default should be 0, but that'll break backwards compatibility. If we change it, it should be a 2-step process:

- Make it configurable with a default of 1, but show a warning if the user hasn't passed an explicit value.
- Change the default to 0 in a future release.

**Comment by alf** [comment]
Thanks. When do you plan the next release? :)

**Comment by TomasTomecek** [comment]
Getting this on engine 1.8 with docker-py-1.7rc2
```
  Scenario: Starting the PTY againt container with disabled logging           # features/interactive_terminal.feature:33
    Given I am using a TTY                                                    # features/steps/step_definitions.py:61 0.000s
    And I run "/bin/sh" in a docker container with a PTY and disabled logging # features/steps/step_definitions.py:83 0.137s
    When I start dockerpty                                                    # features/steps/step_definitions.py:127 2.318s
    Then I will see the output                                                # features/steps/step_definitions.py:186 0.001s
      """
      / #
      """
      Assertion Failed: Expected [u"Error attaching: Failed to get logging factory: logger: no log driver named 'none' is registered"] to equal [u'/ #']
      Captured stdout:
      actual = Error attaching: Failed to get logging factory: logger: no log driver named 'none' is registered
      wanted = [u'/ #']

```

```
Containers: 479
Images: 446
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.8-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.682 GiB
Name: quahog
ID: PD35:TRT5:VF5I:YQBZ:WR5T:DDLP:GAGB:M374:EK7G:ITUG:6PN3:OCCI
Registry: https://index.docker.io/v1/
```
