### ISSUE TITLE
Need support for custom detachKeys

### ISSUE THREAD

**Issue by qinix** [d11wtq/dockerpty#68]
I'm an emacs user and every time I want to use ctrl-p, I have to type it twice since ctrl-p is the prefix of the detachKeys.
docker already has a config file which can change the detachKeys, docker/docker#3519. But it doesn't work in docker-compose.

Someone who also get trouble in this issue. #62

**Comment by thiagowfx** [comment]
The upstream issue has been closed, so this one could probably be closed too.

**Edit:** actually, nevermind, I think I've misunderstood this issue.
